language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  global:
  - PINS="mirage-kv:. mirage-device.2.0.0:git+https://github.com/hannesm/mirage-device.git#easy"
  - PACKAGE="mirage-kv"
  matrix:
  - OCAML_VERSION=4.06
  - OCAML_VERSION=4.07
  - OCAML_VERSION=4.08
  - OCAML_VERSION=4.09
